apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookmarker-api-pv
spec:
  storageClassName: 'standard'
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Mi
  hostPath:
    path: /var/logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookmarker-api-log-pv-claim
spec:
  storageClassName: 'standard'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  name: bookmarker-api-svc
spec:
  type: NodePort
  selector:
    app: bookmarker-api-pod
  ports:
    - name: app-port-mapping
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmarker-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmarker-api-pod
  template:
    metadata:
      labels:
        app: bookmarker-api-pod
    spec:
      containers:
        - name: bookmarker-api
          image: "jitu1995/bookmarker-api"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: bookmarker-config
                  key: postgres_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: bookmarker-config
                  key: postgres_port
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: bookmarker-config
                  key: postgres_dbname
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bookmarker-secrets
                  key: postgres_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookmarker-secrets
                  key: postgres_password
            - name: LOG_DIR
              valueFrom:
                configMapKeyRef:
                  key: log_dir
                  name: bookmarker-config
          volumeMounts:
            - mountPath: /var/logs
              name: bookmark-log-storage
      volumes:
        - name: bookmark-log-storage
          persistentVolumeClaim:
            claimName: bookmarker-api-log-pv-claim


